# Generated by Django 5.1.2 on 2024-10-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodo', '0001_initial'),
        ('ruta', '0003_remove_ruta_nodo_destino_remove_ruta_nodo_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='ruta',
            name='nodo_fin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ruta_fin', to='nodo.nodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='nodo_inicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ruta_inicio', to='nodo.nodo'),
            preserve_default=False,
        ),
    ]
