# Generated by Django 5.1.2 on 2024-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0004_remove_ruta_fecha_creacion_ruta_nodo_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='tiempo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
