# Generated by Django 5.1.2 on 2024-11-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0006_ruta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
