# Generated by Django 5.1.2 on 2024-11-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0008_remove_ruta_tiempo_ruta_duracion_alter_ruta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Recibido en origen'), (2, 'En tránsito'), (3, 'Llegó a destino'), (4, 'Entregado al destinatario')], default=0),
        ),
    ]
