# Generated by Django 5.1.2 on 2024-10-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='alias',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
