# Generated by Django 5.1.2 on 2024-11-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodo', '0002_nodo_alias'),
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='nodo_actual',
            field=models.ForeignKey(blank=True, help_text='Nodo actual en el que se encuentra el paquete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_actuales', to='nodo.nodo'),
        ),
    ]
