# Generated by Django 5.1.2 on 2024-11-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_paquete_nodo_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
